import { ChevronRight, Clock3, Database, Download, FileJson, Info, LockKeyhole, Moon, Pencil, RotateCcw, Ruler, SunMedium, Target, Trash2 } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import type { AppPreferences, BodyProfile, DailyRecord, ThemeMode } from '../../types/record'
import { exportCSV, exportJSON } from '../../lib/export'
import { parseImport, type ParsedImport } from '../../lib/import'
import { clearRecords, mergeRecords, replaceRecords } from '../../db/records'
import { Modal } from '../../components/ui/Modal'
import { Toast } from '../../components/ui/Toast'
import { BodyEditor } from '../../components/forms/BodyEditor'
import { calculateBMI } from '../../lib/calculations'
import { planRecordMerge } from '../../lib/restore'
import { DecimalInput } from '../../components/ui/DecimalInput'
import { preferencesAfterImport } from '../../lib/preferences'

const LAST_BACKUP_KEY='light-balance:last-json-export'
const backupLabel=(value:string)=>{if(!value)return'尚未导出';const date=new Date(value);if(Number.isNaN(date.getTime()))return'尚未导出';const today=new Date();return date.toDateString()===today.toDateString()?`今天 ${date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:date.toLocaleDateString('zh-CN',{year:'numeric',month:'numeric',day:'numeric'})}
const backupIsOverdue=(value:string,hasRecords:boolean)=>{if(!hasRecords)return false;const timestamp=new Date(value).getTime();return !Number.isFinite(timestamp)||Date.now()-timestamp>30*24*60*60*1000}

export function SettingsPage({records,calculatedRecords,bodyDefaults,proteinTargetGrams,onPreferencesChange,onUpdateBody,theme,setTheme,onRecordsChange}:{records:DailyRecord[];calculatedRecords:DailyRecord[];bodyDefaults:BodyProfile;proteinTargetGrams?:number;onPreferencesChange:(preferences:AppPreferences)=>void;onUpdateBody:(body:BodyProfile)=>Promise<void>;theme:ThemeMode;setTheme:(t:ThemeMode)=>void;onRecordsChange:()=>void}) {
 const fileRef=useRef<HTMLInputElement>(null),[pending,setPending]=useState<ParsedImport|null>(null),[restoring,setRestoring]=useState(false),[erasing,setErasing]=useState(false),[toast,setToast]=useState(''),[editingBody,setEditingBody]=useState(false),[editingTarget,setEditingTarget]=useState(false),[targetDraft,setTargetDraft]=useState<number>(),[targetError,setTargetError]=useState(''),[lastBackupAt,setLastBackupAt]=useState(()=>{try{return localStorage.getItem(LAST_BACKUP_KEY)??''}catch{return''}})
 const mergePlan=useMemo(()=>pending?planRecordMerge(records,pending.records):null,[pending,records])
 const hasLocalData=records.length>0||proteinTargetGrams!=null
 const show=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),1800)}
 const pick=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]; if(!file)return; try{setPending(parseImport(await file.text(),file.name))}catch(error){show(error instanceof Error?error.message:'无法读取文件')} finally {e.target.value=''} }
 const rememberBackup=()=>{const timestamp=new Date().toISOString();try{localStorage.setItem(LAST_BACKUP_KEY,timestamp)}catch{void 0}setLastBackupAt(timestamp)}
 const restore=async(mode:'merge'|'replace')=>{if(!pending||restoring)return;setRestoring(true);try{if(mode==='merge'){const result=await mergeRecords(pending.records);onPreferencesChange(preferencesAfterImport({proteinTargetGrams},pending.preferences,mode));show(result.skipped?`已新增 ${result.added} 条，保留本机 ${result.skipped} 条`:`已新增 ${result.added} 条记录`)}else{if(hasLocalData){exportJSON(records,'天天减脂恢复前备份',{proteinTargetGrams});rememberBackup()}await replaceRecords(pending.records);onPreferencesChange(preferencesAfterImport({proteinTargetGrams},pending.preferences,mode));show(hasLocalData?`已备份本机并导入 ${pending.records.length} 条`:`已导入 ${pending.records.length} 条记录`)}setPending(null);onRecordsChange()}catch{show('导入失败，请重试')}finally{setRestoring(false)}}
 const erase=async()=>{if(erasing||!confirm('确认清空所有健康记录？此操作无法撤销，请先导出 JSON 备份。'))return;if(!confirm('再次确认：永久删除所有本地数据？'))return;setErasing(true);try{await clearRecords();onPreferencesChange({});onRecordsChange();show('所有记录已清空')}catch{show('清空失败，请重试')}finally{setErasing(false)}}
 const backup=()=>{try{exportJSON(records,'天天减脂备份',{proteinTargetGrams});rememberBackup();show('JSON 备份已导出')}catch{show('导出失败，请重试')}}
 const exportCsv=()=>{try{exportCSV(calculatedRecords);show('CSV 已导出')}catch{show('导出失败，请重试')}}
 const openTarget=()=>{setTargetDraft(proteinTargetGrams);setTargetError('');setEditingTarget(true)}
 const saveTarget=()=>{if(targetDraft==null||targetDraft<10||targetDraft>500){setTargetError('请输入 10–500 g');return}onPreferencesChange({proteinTargetGrams:targetDraft});setEditingTarget(false);show('蛋白质目标已保存')}
 const clearTarget=()=>{onPreferencesChange({});setEditingTarget(false);show('蛋白质目标已清除')}
 const backupOverdue=backupIsOverdue(lastBackupAt,hasLocalData)
 const appearances:Array<[ThemeMode,string,typeof SunMedium]>=[['system','跟随系统',SunMedium],['light','浅色',SunMedium],['dark','深色',Moon]]
  return <main className="page settings-page"><header className="page-header"><div><p className="eyebrow">本机与隐私</p><h1>设置</h1></div></header>
  <section className="settings-section"><h2>身体资料</h2><button className="measurement-card" onClick={()=>setEditingBody(true)}><span className="measurement-symbol"><Ruler size={22}/></span><span><strong>{bodyDefaults.weightKg?.toLocaleString()??'—'} kg</strong><em>{bodyDefaults.sex==='male'?'男':bodyDefaults.sex==='female'?'女':'性别未填'} · {bodyDefaults.ageYears?.toLocaleString()??'—'} 岁 · {bodyDefaults.heightCm?.toLocaleString()??'—'} cm · BMI {calculateBMI(bodyDefaults.weightKg,bodyDefaults.heightCm)?.toFixed(1)??'—'}</em></span><Pencil size={17}/></button></section>
  <section className="settings-section"><h2>每日目标</h2><div className="settings-card"><button onClick={openTarget}><span className="setting-icon"><Target/></span><span><strong>蛋白质</strong><small>{proteinTargetGrams==null?'未设置':`${proteinTargetGrams.toLocaleString()} g / 天`}</small></span><ChevronRight/></button></div></section>
  <section className="settings-section"><h2>外观</h2><div className="appearance-grid">{appearances.map(([id,label,Icon])=><button key={id} aria-pressed={theme===id} className={theme===id?'active':''} onClick={()=>setTheme(id)}><Icon size={20}/><span>{label}</span></button>)}</div></section>
  <section className="settings-section"><h2>数据管理</h2><div className="settings-card"><button onClick={exportCsv}><span className="setting-icon"><Download/></span><span><strong>导出 CSV</strong></span><ChevronRight/></button><button onClick={backup}><span className="setting-icon"><FileJson/></span><span><strong>导出 JSON</strong><small>上次导出：{backupLabel(lastBackupAt)}</small></span><ChevronRight/></button><button onClick={()=>fileRef.current?.click()}><span className="setting-icon"><RotateCcw/></span><span><strong>导入数据</strong><small>JSON 或 CSV</small></span><ChevronRight/></button><input ref={fileRef} type="file" accept="application/json,text/csv,.json,.csv" hidden onChange={pick}/><button className="destructive" disabled={erasing} onClick={erase}><span className="setting-icon"><Trash2/></span><span><strong>{erasing?'清空中…':'清空所有数据'}</strong><small>不可恢复</small></span><ChevronRight/></button></div>{backupOverdue&&<div className="backup-reminder"><Clock3 size={15}/><span>{lastBackupAt?'超过 30 天未备份':'尚未备份'}</span><button type="button" onClick={backup}>立即备份</button></div>}</section>
  <section className="privacy-card"><LockKeyhole size={25}/><div><strong>仅保存在本机</strong><p>请定期导出 JSON 备份。</p></div></section>
  <section className="settings-section"><h2>单位</h2><div className="unit-row"><span>体重 <strong>kg</strong></span><span>长度 <strong>cm</strong></span><span>能量 <strong>kcal</strong></span></div></section>
  <section className="settings-section"><h2>关于</h2><div className="settings-card"><div className="setting-static"><span className="setting-icon"><Database/></span><span><strong>存储方式</strong><small>IndexedDB · 仅此设备</small></span></div><div className="setting-static"><span className="setting-icon"><Info/></span><span><strong>天天减脂</strong><small>版本 1.0.0</small></span></div></div></section>
  {editingBody&&<BodyEditor value={bodyDefaults} onClose={()=>setEditingBody(false)} onSave={async body=>{await onUpdateBody(body);setEditingBody(false);show('身体资料已保存')}}/>}
  {editingTarget&&<Modal title="蛋白质目标" onClose={()=>setEditingTarget(false)}><div className="goal-editor"><label><span>每日目标</span><span className="unit-input"><DecimalInput value={targetDraft} onValueChange={value=>{setTargetDraft(value);setTargetError('')}} placeholder="例如 120"/><small>g</small></span></label>{targetError&&<p role="alert">{targetError}</p>}<div className={`goal-actions ${proteinTargetGrams==null?'single':''}`}>{proteinTargetGrams!=null&&<button type="button" className="secondary-button" onClick={clearTarget}>清除目标</button>}<button type="button" className="primary-button" onClick={saveTarget}>保存</button></div></div></Modal>}
  {pending&&mergePlan&&<Modal title="导入数据" dismissible={!restoring} onClose={()=>setPending(null)}><div className="restore-copy"><strong>{pending.source==='csv'?'CSV':'JSON'} · {pending.records.length} 条记录</strong>{pending.preferences?.proteinTargetGrams!=null&&<p>蛋白质目标：{pending.preferences.proteinTargetGrams.toLocaleString()} g / 天</p>}<p>合并：新增 {mergePlan.added} 条{mergePlan.skipped>0?`，保留本机 ${mergePlan.skipped} 条同日记录`:''}</p><p>覆盖：{hasLocalData?'先备份本机，再替换全部记录':'导入文件中的全部记录'}</p></div><div className="modal-actions"><button className="secondary-button" disabled={restoring} onClick={()=>restore('merge')}>{restoring?'导入中…':'安全合并'}</button><button className="danger-fill" disabled={restoring} onClick={()=>restore('replace')}>{restoring?'请稍候':hasLocalData?'备份并覆盖':'全部导入'}</button></div></Modal>}{toast&&<Toast>{toast}</Toast>}
 </main>
}
