import { useState } from 'react'
import type { BodyProfile } from '../../types/record'
import { Modal } from '../ui/Modal'
import { DecimalInput } from '../ui/DecimalInput'

export function BodyEditor({value,onSave,onClose}:{value:BodyProfile;onSave:(body:BodyProfile)=>Promise<void>;onClose:()=>void}){
  const [heightCm,setHeight]=useState(value.heightCm),[weightKg,setWeight]=useState(value.weightKg),[waistCm,setWaist]=useState(value.waistCm),[ageYears,setAge]=useState(value.ageYears),[sex,setSex]=useState(value.sex),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(heightCm==null||weightKg==null||ageYears==null||!sex){setError('请填写身高、体重、年龄并选择性别');return}if(ageYears<=0||ageYears>130){setError('请输入有效年龄');return}setSaving(true);await onSave({heightCm,weightKg,waistCm,ageYears,sex})}
  return <Modal title="身体资料" onClose={onClose}><form className="entry-form body-editor" onSubmit={submit}><div className="profile-field"><span>性别</span><div className="sex-picker" role="group" aria-label="性别"><button type="button" className={sex==='male'?'active':''} onClick={()=>{setSex('male');setError('')}}>男</button><button type="button" className={sex==='female'?'active':''} onClick={()=>{setSex('female');setError('')}}>女</button></div></div><label><span>年龄</span><span className="unit-input"><DecimalInput required value={ageYears} onValueChange={value=>{setAge(value);setError('')}} placeholder="30"/><small>岁</small></span></label><label><span>身高</span><span className="unit-input"><DecimalInput required value={heightCm} onValueChange={value=>{setHeight(value);setError('')}} placeholder="175"/><small>cm</small></span></label><label><span>体重</span><span className="unit-input"><DecimalInput required value={weightKg} onValueChange={value=>{setWeight(value);setError('')}} placeholder="75,25"/><small>kg</small></span></label><label><span>腰围 <small>可选</small></span><span className="unit-input"><DecimalInput value={waistCm} onValueChange={setWaist} placeholder="84,5"/><small>cm</small></span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={saving}>{saving?'保存中…':'保存'}</button></form></Modal>
}
